name: JoinMessagePlus
version: 3.3
api-version: 1.13
authors: [AndyCraftz, MrKinau]
website: https://andycraftz.eu
main: eu.andycraftz.joinmessageplus.bukkit.JoinMessagePlus
softdepend: [Essentials, PlaceholderAPI, AuthMe]
commands:
