name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v2
        
      - name: Set Env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV

      - name: Set up JDK 1.8
        id: setup_jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache local Maven repository
        id: cache_maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: '${{ runner.os }}-m2-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: '${{ runner.os }}-m2'

      - name: Build with Maven
        id: build_using_maven
        run: mvn --batch-mode --update-snapshots verify
        
      - name: Upload Plugin
        uses: actions/upload-artifact@v2
        with:
          name: JoinMessagePlus-${{ env.GITHUB_SHA_SHORT }}.jar
          path: target/JoinMessagePlus.jar
